### ISSUE TITLE
send_file hangs when using microdot_asyncio bug 

### ISSUE THREAD

**Issue by acamu** [miguelgrinberg/microdot#180]
**Describe the bug**
send_file hangs when using microdot_asyncio but works fine with microdot.

**To Reproduce**

```
from microdot_asyncio import Microdot, Response
from microdot import send_file 

app = Microdot()
Response.default_content_type = 'text/html'

@app.route('/')
def index(req):
    return send_file("test.html")

app.run(debug=True)
```

**Expected behavior**
Browser should return the web page, but instead it hangs

**The stacktrace**
```
Task exception wasn't retrieved
future: <Task> coro= <generator object 'serve' at 3f8b0a20>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "microdot_asyncio.py", line 269, in serve
  File "microdot_asyncio.py", line 342, in handle_request
  File "microdot_asyncio.py", line 158, in write
  File "uasyncio/stream.py", line 1, in stream_awrite
  File "uasyncio/stream.py", line 1, in write
TypeError: object with buffer protocol required
```

For the test.html you can use what you want :)

**Comment by acamu** [comment]
After searching in the code the folling import working

from microdot_asyncio import send_file

I didn't pay attention when i copy the import in the documentation (which describ the sync microdot)
