### ISSUE TITLE
Static example with multiple images fails on ESP32

### ISSUE THREAD

**Issue by Kamosh** [miguelgrinberg/microdot#273]
I would like to use the microdot on ESP32 that would serve as a small webserver/controller for a fishfeeder.
My code runs fine when it is executed on PC but when I move the code on ESP32 then it fails on errors like
```
Task exception wasn't retrieved
future: <Task> coro= <generator object 'serve' at 3ffe9410>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "/lib/microdot.py", line 1228, in serve
  File "/lib/microdot.py", line 1340, in handle_request
  File "/lib/microdot.py", line 659, in write
  File "asyncio/stream.py", line 1, in stream_awrite
  File "asyncio/stream.py", line 1, in drain
OSError: [Errno 113] ECONNABORTED
```

It seems that if multiple files are served concurrently from the microdot on ESP32 via wifi then it has this problem.

**To Reproduce**
I created a simplified example of your "static" example. Please find a diff for the "static" example on https://github.com/miguelgrinberg/microdot/compare/main...Kamosh:microdot:esp32_concurrent_send_file_issue .

I uploaded code the ESP32 and ran the static.py, the syspath set to include microdot libraries.

Using Chrome browser on my PC browser I am able to sometimes see whole screen served from ESP32 for the first time. But the refresh of the page fails with the mentioned error.

Complete logs:
```
Connecting to WiFi Network Name: janevim3
Waiting for wifi chip to power up...
Waiting for access point to log us in.
Success! We have connected to your access point!
Try to ping the device at 192.168.10.109
Starting async server on 0.0.0.0:5000...
GET / 200
GET /static/logo1.png 200
GET /static/logo2.png 200
GET /static/logo3.png 200
GET /static/logo4.png 200
GET /favicon.ico 404
GET / 200
Task exception wasn't retrieved
future: <Task> coro= <generator object 'serve' at 3ffe9410>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "/lib/microdot.py", line 1228, in serve
  File "/lib/microdot.py", line 1340, in handle_request
  File "/lib/microdot.py", line 659, in write
  File "asyncio/stream.py", line 1, in stream_awrite
  File "asyncio/stream.py", line 1, in drain
OSError: [Errno 113] ECONNABORTED
Task exception wasn't retrieved
future: <Task> coro= <generator object 'serve' at 3ffda400>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "/lib/microdot.py", line 1228, in serve
  File "/lib/microdot.py", line 1340, in handle_request
  File "/lib/microdot.py", line 659, in write
  File "asyncio/stream.py", line 1, in stream_awrite
  File "asyncio/stream.py", line 1, in drain
OSError: [Errno 113] ECONNABORTED
Task exception wasn't retrieved
future: <Task> coro= <generator object 'serve' at 3ffdea50>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "/lib/microdot.py", line 1228, in serve
  File "/lib/microdot.py", line 1340, in handle_request
  File "/lib/microdot.py", line 659, in write
  File "asyncio/stream.py", line 1, in stream_awrite
  File "asyncio/stream.py", line 1, in drain
OSError: [Errno 113] ECONNABORTED
Task exception wasn't retrieved
future: <Task> coro= <generator object 'serve' at 3ffde090>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "/lib/microdot.py", line 1228, in serve
  File "/lib/microdot.py", line 1340, in handle_request
  File "/lib/microdot.py", line 659, in write
  File "asyncio/stream.py", line 1, in stream_awrite
  File "asyncio/stream.py", line 1, in drain
OSError: [Errno 113] ECONNABORTED
```

**Expected behavior**
I would like to get whole page with all images on it without any error. It would be really great if I could continue with my FishFeeder project :-)

**Additional context**
I found that somethin similar has been already discussed here https://github.com/orgs/micropython/discussions/14427

**Comment by miguelgrinberg** [comment]
The high-level response is that Microdot assumes that the networking system is functional, which isn't always the case. It seems that when there is too much network activity the network may crash and disconnect. The issue that you linked has a number of suggestions you can try. Also see https://github.com/miguelgrinberg/microdot/discussions/271.

If the `OSError` exception you are receiving interrupts the server then you should be able to catch it with a try/except block around the `app.run()` call. At that point you can attempt to reconnect the network and then start the server again.
