### ISSUE TITLE
File "microdot.py", line 25 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by QGB** [miguelgrinberg/microdot#65]
```
>>> import microdot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "microdot.py", line 25
SyntaxError: invalid syntax

```
upip install to /Lib/src ,so I directly save https://github.com/miguelgrinberg/microdot/blob/main/src/microdot.py to esp32c3 board

**Comment by miguelgrinberg** [comment]
What do you have in line 25 of microdot.py? Do not look in github please, look in the copy of the file that was installed on your device.

**Comment by QGB** [comment]
@miguelgrinberg 
```
import upip
upip.install('microdot')
```

it is the correct way to install microdot in esp32 board?
