### ISSUE TITLE
utemplate raise error on keyword argument

### ISSUE THREAD

**Issue by Gingso** [miguelgrinberg/microdot#72]
Hi Miguel,

the utemplate integration raise an error on keyword.  It seems like there is something missing in microdot_utemplate.py

Code snipped:

`import uasyncio as asyncio
from microdot_asyncio import Microdot, Response
from microdot_utemplate import render_template

app = Microdot()
Response.default_content_type = 'text/html'

..........

@app.route('/')
async def mainpage(request):
    name='myname'
    return render_template(template='index.html', location=name)`

When I connect to the webserver it crashes:

`Traceback (most recent call last):
  File "/lib/microdot_asyncio.py", line 367, in dispatch_request
  File "/lib/microdot_asyncio.py", line 423, in _invoke_handler
  File "<stdin>", line 130, in mainpage
  File "/lib/microdot_utemplate.py", line 34, in render_template
TypeError: unexpected keyword argument 'location'`

what i figured out so far:

> in templates an index_html.py file is generated

        --> If i copy paste the included render function to my code and execute directly, everything works fine.

> It looks like an issue with the loader / Load function in microdot_utemplate.py:

`  if _loader is None:  # pragma: no cover
        init_templates()
    render = _loader.load(template)
    return render(*args, **kwargs)`

any ideas how to fix this?

P.S.: Environment: ESP32 with latest micropython OTA firmware, packages installed whith Thonny's packet manager.

Thanks
 Gingso

**Comment by Gingso** [comment]
I had a typo in the template, sorry.
